//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.02 at 10:23:42 PM CEST 
//


package packages.service.jaxb;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "tableMap", "steps" })
@XmlRootElement(namespace = "http://arpi.io/game/gol-web-service", name = "getTableStateResponse")
public class GetTableStateResponse {

	@XmlElement
	@XmlJavaTypeAdapter(MapAdapter.class)
	private Map<Integer, List<String>> tableMap = new HashMap<>();

	@XmlElement(namespace = "http://arpi.io/game/gol-web-service", required = true)
	protected int steps;
	
	public int getSteps() {
		return steps;
	}

	public void setSteps(int steps) {
		this.steps = steps;
	}

	public Map<Integer, List<String>> getTableMap() {
		return tableMap;
	}

	public void setTableMap(Map<Integer, List<String>> tableMap) {
		this.tableMap = tableMap;
	}
	
}
